### ISSUE TITLE
1 - User Management Login-Register

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#1]
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) to leverage/use services and information that are exclusively available to registered users.

## Acceptance criteria
- [x] sopra-fs22-group-27/Pictionary-Client#1
- [x] sopra-fs22-group-27/Pictionary-Client#2
- [x] sopra-fs22-group-27/Pictionary-Server#16
- [x] sopra-fs22-group-27/Pictionary-Client#4

**Comment by SyLi9527** [comment]
Done in #59,
it showed failed since I didn't change the tests. Now the tests have been deleted.
