### ISSUE TITLE
10 - Customize a Game

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#10]
As the creator of the game, I want to be able to customize the game.
## Acceptance criteria
- The user is able to customize the game
- The user is able to set the maximal player count
- The user is able to set time limits
- The user is able to set party to open/private

## Development Tasks
- [x] sopra-fs22-group-27/Pictionary-Client#11
- [x] sopra-fs22-group-27/Pictionary-Client#10
- [x] sopra-fs22-group-27/Pictionary-Client#9
