### ISSUE TITLE
2 - User Management Edit

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#2]
As a logged-in user I want to edit my user profile to set/update my personal information. 

## Acceptance criteria
- A logged-in user is able to set his personal information
- A logged-in user is able to update his personal information

## Development Tasks
- [x] sopra-fs22-group-27/Pictionary-Client#7
- [x] sopra-fs22-group-27/Pictionary-Client#5
- [x] sopra-fs22-group-27/Pictionary-Client#14
- [x] sopra-fs22-group-27/Pictionary-Client#28
- [x] #87 
- [x] #88
- [x] #89
