### ISSUE TITLE
5 - Play a turn as ‘Drawer’

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#5]
As an active player whose turn it is to draw, I want to be given an object to draw and a set time to complete the drawing.

## Acceptance criteria
- A User is able to play the game as a drawer and is able to draw the given object.

## Development Tasks
- [x] sopra-fs22-group-27/Pictionary-Client#20
- [x] sopra-fs22-group-27/Pictionary-Client#19
- [x] sopra-fs22-group-27/Pictionary-Client#6
- [x] sopra-fs22-group-27/Pictionary-Client#39
- [x] sopra-fs22-group-27/Pictionary-Client#40
- [x] sopra-fs22-group-27/Pictionary-Client#42
