### ISSUE TITLE
20 - Styling

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#62]
As a user, I want to perceive the application as a good and modern application that I perceive as appealing.

- [x] sopra-fs22-group-27/Pictionary-Client#30
- [x] sopra-fs22-group-27/Pictionary-Client#31
- [x] sopra-fs22-group-27/Pictionary-Client#32
- [x] sopra-fs22-group-27/Pictionary-Client#33
- [x] sopra-fs22-group-27/Pictionary-Client#34
- [x] sopra-fs22-group-27/Pictionary-Client#35
- [x] sopra-fs22-group-27/Pictionary-Client#36
- [ ] sopra-fs22-group-27/Pictionary-Client#38
