### ISSUE TITLE
7 - Play a turn as ‘Guesser’

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#7]
As an active player whose turn it is to guess, I want to see the drawing at the same time as every other player and submit my guess.

## Acceptance criteria
- A user is able to submit his guess
- A user is able to see the drawing

## Development Tasks
- [x] sopra-fs22-group-27/Pictionary-Client#21
- [x] sopra-fs22-group-27/Pictionary-Client#22
- [x] sopra-fs22-group-27/Pictionary-Client#23
- [x] sopra-fs22-group-27/Pictionary-Client#65

**Comment by mrspacerobot** [comment]
started work on drawer branch
